version: "3"
services:
  db:
    image: postgres:12
    ports:
      - "${POSTGRESQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}: 6379"
    command: ['--requirepass "secret"']

#for data to persist
volumes:
  postgres: ~
